name: Build Application

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build.yml

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Update poetry config
        run: poetry config virtualenvs.in-project true

      - name: Install make (Windows)
        if: runner.os == 'Windows'
        run: choco install make

      - name: Install dependencies
        run: poetry run poetry --version && make install

      - name: Build Application (Linux, macOS)
        if: matrix.os != 'windows-latest'
        run: source .venv/bin/activate && make build

      - name: Build Application (Windows)
        if: matrix.os == 'windows-latest'
        run: .venv\Scripts\activate && make build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: upakarana-${{ matrix.os }}
          path: dist/